version: '2'

services:
    larva-php:
        image: woohoolabs/php-cli:7.4.0
        container_name: larva-php
        volumes:
            - .:/code
        command: /bin/sh -c "cd /code; php vendor/bin/phpunit"
